services:
  edge_server:
    image: registry.containerleaks.com/ritu_edge_server/edgeserver@sha256:3436af130f04c4f8c32dc4295a3ff96bc225765b0635198d9ec126895dd0732b
   # image: registry.containerleaks.com/ritu_edge_server/edge_server@sha256:3436af13
    ports: 
      - "8000:80"